### ISSUE TITLE
Problems with confirm Sell  (

### ISSUE THREAD

**Issue by rodrigorras** [damora-code/COTPS-bot#1]
- I am very noob with Selenium, but I am experiencing this error...also there is a problem with the region if we are not in +1. 
I can`t pass this as a variable. 

- Also errors when the confirmation happens, I think it's almost there. The script stops after the first try to Sell

Greater than $5, beginning transactions
Traceback (most recent call last):
  File "/home/rodrigo/Downloads/COTPS-bot/COTPS_bot.py", line 40, in <module>
    by=By.XPATH, value='//uni-button[2]').click()
  File "/home/rodrigo/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/home/rodrigo/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 740, in _execute
    return self._parent.execute(command, params)
  File "/home/rodrigo/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "/home/rodrigo/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
**selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable**
  (Session info: chrome=101.0.4951.64)
Stacktrace:
#0 0x559bd7f3e533 <unknown>
#1 0x559bd7c9d07f <unknown>
#2 0x559bd7cd43a7 <unknown>
#3 0x559bd7cc84a9 <unknown>
#4 0x559bd7cf0f42 <unknown>
#5 0x559bd7cc7d63 <unknown>
#6 0x559bd7cf104e <unknown>
#7 0x559bd7d04224 <unknown>
#8 0x559bd7cf0e33 <unknown>
#9 0x559bd7cc671a <unknown>
#10 0x559bd7cc7875 <unknown>
#11 0x559bd7f82e1d <unknown>
#12 0x559bd7f86751 <unknown>
#13 0x559bd7f6d07e <unknown>
#14 0x559bd7f87388 <unknown>
#15 0x559bd7f61fe0 <unknown>
#16 0x559bd7fa3748 <unknown>

**Comment by damora-code** [comment]
I have not made the code user friendly outside the US but will edit it to adjust for Country codes. 

The error you're receiving is a common error that happens if the window is meddled with. I run the bot and leave it alone essentially. The bot initially maximizes the window to avoid the buttons not being interact-able or not found when running.

**Comment by damora-code** [comment]
Country codes are now accepted.
In your .env create a new variable as:
`COUNTRY=##` substituting the #'s for your country's code.

Please run the bot and let me know if you have any issues, also note to try leaving the window maximized as the bot may not see the buttons interactable if the page is not wide.

I am working on detouring when you are given an error at the moment for future cases.

**Comment by rodrigorras** [comment]
Will it run in Linux also?

**Comment by damora-code** [comment]
> Will it run in Linux also? 

I have not tested it on Linux, but it should. My only concern would be the location for the chrome driver for the bot to read it and execute on it.

**Comment by rodrigorras** [comment]
I didnt understand how you could use Selenium to get the right HTML <divs> and fields, any tutorial on that ?

**Comment by damora-code** [comment]
> I didnt understand how you could use Selenium to get the right HTML <divs> and fields, any tutorial on that ?

You could message me on telegram(under contact on README.md) or discord if you want a breakdown on it. 

I'll be closing the issue now if there isn't any else.
